spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://svc.sel5.cloudtype.app:32119/postgres
    platform: postgres
    username: root
    password: mydb123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true

graphql:
  spqr:
    gui:
      enabled: true
